name: MAUI Unit Tests
 
on:
  push:
    branches:
      - main
      - develop
      - feature-uc18
      - feature-uc19    
      - infra/runner-toevoegen
  pull_request:
    branches:
      - main
      - develop
 
jobs:
  test:
    runs-on: ubuntu-latest  # Of windows-latest/macOS-latest als specifiek platform nodig is
    steps:
      - name: Haal de repository op
        uses: actions/checkout@v4
 
      - name: Installeer .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Gebruik de juiste versie voor MAUI
 
      - name: Herstel afhankelijkheden
        run: dotnet restore ./TestCore/TestCore.csproj
 
      - name: Bouw TestCore
        run: dotnet build ./TestCore/TestCore.csproj --configuration Release --no-restore
 
      - name: Voer unit tests uit
        run: dotnet test ./TestCore/TestCore.csproj --configuration Release --no-restore --no-build --verbosity normal
